name: CI

# Cancel previous runs that are not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "production"

permissions:
  contents: write
  actions: read

jobs:
  ci:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Docker build project
        run: echo "Docker build image"